{
 "title": "kkim",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_vin",
    "label": "VIN",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"demo\", tag: \"vin\")\n"
   }
  ]
 },
 "panels": [
  { "title": "Driving History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Driving Score",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"acceleratorPedalposition\")\n  |> difference(columns: [\"_value\"], nonNegative: false)\n  |> map(fn: (r) => {\n      _num = if (r._value >= 20.0) then 1.0 else 0.0\n      return {\n        _time: r._time,\n        _value: _num,\n        vin: r.vin\n      }\n  })\n  |> sum()"
    },
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wheelBasedSpeed\")\n  |> difference(columns: [\"_value\"], nonNegative: false)\n  |> map(fn: (r) => {\n      _num = if (r._value >= 20.0) then 1.0 else 0.0\n      return {\n        _time: r._time,\n        _value: _num,\n        vin: r.vin\n      }\n  })\n  |> sum()"
    },
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"brakeCircuit1Pedalposition\")\n  |> difference(columns: [\"_value\"], nonNegative: false)\n  |> map(fn: (r) => {\n      _num = if (r._value >= 20.0) then 1.0 else 0.0\n      return {\n        _time: r._time,\n        _value: _num,\n        vin: r.vin\n      }\n  })\n  |> sum() "
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wheelBasedSpeed\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"vin\"])\n  |> group(columns: [\"vin\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Accelerator",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"acceleratorPedalposition\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"vin\"])\n  |> group(columns: [\"vin\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Average Speed Change",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wheelBasedSpeed\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"vin\"])\n  |> group(columns: [\"vin\"])\n  // 속도 변화량 계산\n  |> difference(columns: [\"_value\"], nonNegative: false)\n  // 변화량의 절대값 계산\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: if (r._value < 0.0) then (r._value * -1.0) else (r._value) + 10.0,\n      vin: r.vin\n    }))\n  // 평균 계산\n  |> mean(column: \"_value\")\n  |> yield(name: \"average_speed_variation\")\n"
    }
   ]
  },
  {
   "title": "Speed Change",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wheelBasedSpeed\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"vin\"])\n  |> group(columns: [\"vin\"])\n  // 속도 변화량 계산\n  |> difference(columns: [\"_value\"], nonNegative: false)\n  // 변화량의 절대값 계산\n  |> map(fn: (r) => {\n      _abs_diff = if (r._value < 0.0) then (r._value * -1.0) else (r._value)\n      return {\n        _time: r._time,\n        _value: _abs_diff,\n        vin: r.vin\n      }\n  })\n  |> yield(name: \"speed_variation\")\n"
    }
   ]
  },
  {
   "title": "Brake",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"brakeCircuit1Pedalposition\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"vin\"])\n  |> group(columns: [\"vin\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Driver Working State",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"driver1WorkingState\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"vin\", \"_value\", \"_time\", \"_field\"])\n  |> group(columns: [\"vin\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Time Related Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"driver1WorkingState\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"vin\", \"_value\", \"_time\", \"_field\"])\n  |> group(columns: [\"vin\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Sudden Brakes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tachographSpeed\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"vin\"])\n  |> group(columns: [\"vin\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> duplicate(column: \"_value\", as: \"original_value\")\n  // 변화량 계산\n  |> difference(columns: [\"_value\"], nonNegative: false)\n  // 새로운 필드 diff에 변화량의 절대값 저장\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _diff: if ((r.original_value - r._diff) == 0) then 0.0 else (r.original_value / (r.original_value - r._value) - 1.0) * 100.0,\n      vin: r.vin\n    }))\n  |> filter(fn: (r) => r[\"_diff\"] < -50 )\n  |> yield(name: \"with_abs_diff\")\n"
    }
   ]
  },
  {
   "title": "Sudden Brakes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tachographSpeed\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"vin\"])\n  |> group(columns: [\"vin\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> duplicate(column: \"_value\", as: \"original_value\")\n  // 변화량 계산\n  |> difference(columns: [\"_value\"], nonNegative: false)\n  // 새로운 필드 diff에 변화량의 절대값 저장\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _diff: if ((r.original_value - r._diff) == 0) then 0.0 else (r.original_value / (r.original_value - r._value) - 1.0) * 100.0,\n      vin: r.vin\n    }))\n  |> filter(fn: (r) => r[\"_diff\"] < -50 )\n  |> map(fn: (r) => ({\n    _time: r._time,\n    log: string(v: r._diff),\n    vin: r.vin\n  }))\n  |> yield(name: \"with_abs_diff\")\n"
    }
   ]
  },
  { "title": "Car Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "BrakePad Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fuelLevel1\" or r[\"_field\"] == \"catalystFuelLevel\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"vin\"])\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Fuel Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fuelLevel1\" or r._field == \"fuelLevel2\" or r[\"_field\"] == \"catalystFuelLevel\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"vin\"])\n  |> group(columns: [\"vin\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "HealthCheck Needed In",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"catalystFuelLevel\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"vin\"])\n  |> group(columns: [\"vin\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Eco-friendly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CO2 Emission",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snapshot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fuelLevel1\")\n  |> filter(fn: (r) => contains(set: ${selected_vin:json}, value: r[\"vin\"]))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"vin\"])\n  |> group(columns: [\"vin\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}